name: Continuous Integration
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    name: build - fmt/lint/test
    env:
      ENVIRONMENT: ci
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run fmt
      run: make fmt
    - name: Run lint
      run: make lint
    - name: Run tests
      run: make test

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    name: release
    env:
      ENVIRONMENT: ci
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: make test

    - name: Upload coverage to Codecov
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
    
    - name: Run tag export
      run: ./scripts/ci/tag.sh
